### ISSUE TITLE
cracker does not work for dollargeneral

### ISSUE THREAD

**Issue by triton-gitworld** [ziplokk1/incapsula-cracker-py3#1]
This cracker does not works for dollargeneral.com which uses incapsula captcha.

**Comment by ziplokk1** [comment]
Do you have any more details I can use to debug the issue with? I'm not having any issues with the library on my end. Can you post some code snippets?

**Comment by triton-gitworld** [comment]
The response of dollargeneral is like as follows.
<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?CWUDNSAI=9&xinfo=10-145080678-0 0NNN RT(1495689294935 1) q(0 -1 -1 0) r(0 -1) B12(4,315,0) U1&incident_id=485000470549342814-1091780437566882554&edet=12&cinfo=04000000" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 485000470549342814-1091780437566882554</iframe></body></html>

**Comment by triton-gitworld** [comment]
And here is my code snippet.

    def _extract_page_tree(self):
        for i in range(3):
            try:
                with IncapSession() as s:
                    response = s.get(self.START_URL, headers=self.DEFAULT_HEADERS, bypass_crack=True)
                    response = s.get(self.product_page_url, headers=self.DEFAULT_HEADERS)

                    if self.lh:
                        self.lh.add_log('status_code', response.status_code)

                    if response.ok:
                        content = response.text
                        self.tree_html = html.fromstring(content)
                        return

                    else:
                        self.ERROR_RESPONSE['failure_type'] = response.status_code

            except Exception as e:
                print 'ERROR EXTRACTING PAGE TREE', self.product_page_url, e

        self.is_timeout = True  # return failure

**Comment by ziplokk1** [comment]
Ok, I have "solved" the issue. 

The problem was that dollargeneral.com was serving a captcha which wasn't being detected. That issue has now been solved and `s.get()` will now raise an `IncapBlocked` exception which you can catch.

Should be good to go now.

Thank you,
Mark
