### ISSUE TITLE
Using incapsula-cracker-py3 with proxies?

### ISSUE THREAD

**Issue by Swordyjohn** [ziplokk1/incapsula-cracker-py3#21]
How would you configure this to use with proxies? in the previous version you could use "crack" on your requests.session object which has enabled proxies but that doesn't seem to work for this one.

**Comment by mickaelmonsieur** [comment]
Solution?

**Comment by eplaut** [comment]
@mickaelmonsieur `IncapSession` inherit from `requests.Session`, just update `session.proxies` with the relevant dict ({schema: proxy}).

@ziplokk1 I suggest to add *args & **kwargs to `IncapSession.__init__` and pass them to it's `super`
